[package]
name = "swissh"
version = "0.2.0"
edition = "2021"

[dependencies]
smoldot = "0.19.3"
clap = { version = "4.5.38", features = ["derive"] }
sp-core = "36.1.0"
sp-runtime = "41.1.0"
ssh-key = { version = "0.6.7", features = ["encryption", "ed25519"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
home = "0.5.11"
bs58 = "0.5.1"
blake2-rfc = "0.2.18"
hex = "0.4.3"
dirs = "6.0.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
subxt = { version = "0.42", default-features = false, features = ["web"] }
subxt-lightclient = "0.42.1"
tokio = { version = "1", features = ["full"] }
rpassword = "7"
anyhow = "1.0"
thiserror = "2.0"
keyring = "3.6.2"
tempfile = "3.20.0"
